name: Deploy to NPM and CDN

on:
  push:
    branches: [master]

jobs:
  build_and_test:
    name: Build, test and archive artifact
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2

      - name: Log environments
        run: |
          echo "Logging GitHub environments"
          echo "Branch" ${GITHUB_REF##*/}
          echo "GITHUB_REPOSITORY_NAME_SLUG" ${GITHUB_REPOSITORY_NAME_SLUG}
          echo "GITHUB_REF" ${GITHUB_REF}
          echo "GITHUB_REF_NAME" ${GITHUB_REF_NAME}
          echo "GITHUB_REF_NAME_SLUG" ${GITHUB_REF_NAME_SLUG}
          echo "GITHUB_REF_SLUG" ${GITHUB_REF_SLUG}

      - name: Configure NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.1.x"

      - name: Install dependencies and build
        run: |
          cd code
          npm ci
          npm run build --if-present

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          retention-days: 7
          name: tecnologia-design-tokens # artifact name
          path: |
            code/dist

  deploy:
    needs: build_and_test
    name: Deploy to CDN and NPM
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout and log environments
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: tecnologia-design-tokens
          path: code/dist

      # NPM PUBLISH
      - id: publish
        name: Publish to NPM if version has been updated
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./code/package.json
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: ${{ steps.publish.outputs.version }}

      - name: Create Release
        if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          release_name: Release ${{ steps.publish.outputs.version }}
          body: ${{ steps.publish.outputs.version }}
          draft: false
          prerelease: false

      # CDN DEPLOY
      - name: Configure AWS credentials for CDN account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy CDN
        run: |
          sh ./scripts/deploy.sh
        env:
          OLD_VERSION: ${{ steps.publish.outputs.old-version }}
          VERSION: ${{ steps.publish.outputs.version }}
          BASE_PATH: code/
          CI: true
          AWS_CLOUDFRONT_DIST_ID: ${{ secrets.AWS_CLOUDFRONT_DIST_ID }}
          FILE: ./dist/tecnologia-webcomponents/tecnologia-webcomponents.js
